CREATE FUNCTION DBO.AY_ADI(@DATE AS DATETIME)
RETURNS VARCHAR (10)
AS
BEGIN
DECLARE @RESULT AS VARCHAR(10)
IF DATEPART(MONTH,@DATE)=1 SET @RESULT = 'OCAK'
IF DATEPART(MONTH,@DATE)=2 SET @RESULT = 'ÞUBAT'
IF DATEPART(MONTH,@DATE)=3 SET @RESULT = 'MART'
IF DATEPART(MONTH,@DATE)=4 SET @RESULT = 'NÝSAN'
IF DATEPART(MONTH,@DATE)=5 SET @RESULT = 'MAYIS'
IF DATEPART(MONTH,@DATE)=6 SET @RESULT = 'HAZÝRAN'
IF DATEPART(MONTH,@DATE)=7 SET @RESULT = 'TEMMUZ'
IF DATEPART(MONTH,@DATE)=8 SET @RESULT = 'AÐUSTOS'
IF DATEPART(MONTH,@DATE)=9 SET @RESULT = 'EYLÜL'
IF DATEPART(MONTH,@DATE)=10 SET @RESULT = 'EKÝM'
IF DATEPART(MONTH,@DATE)=11 SET @RESULT = 'KASIM'
IF DATEPART(MONTH,@DATE)=12 SET @RESULT = 'ARALIK'
RETURN @RESULT
END

SELECT DBO.AY_ADI('2023-09-26')